// <auto-generated />
namespace WebPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class event_time_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(event_time_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201712280720565_event_time_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
